language: node_js
cache:
  yarn: true
  directories:
    - "node_modules"
node_js:
  - "8"
install:
  - yarn global add codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov